export const SET_LOCATION_TYPE = 'SET_LOCATION';
export const SET_SELECTED_VENUE_ID_TYPE = 'SET_SELECTED_VENUE_ID';
export const SET_MENU_CATEGORY_ID_TYPE = 'SET_MENU_CATEGORY_ID';
export const SET_SELECTED_ITEM_ID_TYPE = 'SET_SELECTED_ITEM_ID';
